title: Scottish Coastal Modelling
description: Modeling of Scottish Coastal Waters: A Road Map
theme: just-the-docs

url: https://masts-nehm.github.io/roadmap/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
